name: airflow_dbt
version: "1.0"
config-version: 2

profile: airflow_postgres

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airflow_dbt:
    staging:
      materialized: view
    marts:
      materialized: table